- name: Configure ACI
  hosts: aci
  connection: local
  gather_facts: false
      
  tasks:

  - name: Create XML POSTS from templates
    template: src={{ item.src }} dest={{ item.dest }}
    with_items:
      - { src: 'ldev.j2',                      dest: 'ldev.xml' }
      - { src: 'contract.j2',                  dest: 'contract.xml' }
      - { src: 'service_graph_template.j2',    dest: 'service_graph_template.xml'}
      - { src: 'deviceSelectionPolicy.j2',     dest: 'deviceSelectionPolicy.xml'}
      - { src: 'apply_graph.j2',               dest: 'apply_graph.xml'}
      - { src: 'attach_cons_prov_contract.j2', dest: 'attach_cons_prov_contract.xml'}

  - name: Execute POSTS
    aci_rest:
      action: "post"
      uri: "/api/node/mo/uni/tn-{{tenant_name}}.xml"
      config_file: "{{ item }}"
      host: "{{inventory_hostname}}"
      username: '{{ lookup("env", "ANSIBLE_NET_USERNAME") }}'
      password: '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'
      validate_certs: "false"
    with_items:
     - "ldev.xml"
     - "contract.xml"
     - "service_graph_template.xml"
     - "deviceSelectionPolicy.xml"
     - "apply_graph.xml"
     - "attach_cons_prov_contract.xml"
